Build: CD 워크플로우 스크립트 최적화 - GitHub Actions 워크플로우에서 Docker 이미지 SHA 기반 배포로 변경 - latest 태그 제거, 이미지 재현성 보장 - EC2 배포 시 Docker Compose 환경변수 IMAGE_TAG 적용 - 오래된 이미지 자동 삭제(prune) 추가

diff --git a/.github/workflows/deploy-dev.yml b/.github/workflows/deploy-dev.yml
--- a/.github/workflows/deploy-dev.yml
+++ b/.github/workflows/deploy-dev.yml
@@ -3,9 +3,13 @@ name: Deploy Dev to EC2
 on:
   pull_request:
     branches:
-      - develop
+      - "develop"
     types:
       - closed
+
+  push:
+    branches:
+      - "develop"
 
 permissions:
   id-token: write
@@ -13,13 +17,12 @@ permissions:
 
 jobs:
   deploy:
-    if: |
-      github.event_name != 'pull_request' ||
-      (github.event.pull_request.merged == true)
+    if: github.event.pull_request.merged == true
+
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
-        uses: actions/checkout@v4
+        uses: actions/checkout@v5
 
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v4
@@ -31,22 +34,37 @@ jobs:
         id: login-ecr
         uses: aws-actions/amazon-ecr-login@v2
 
-      - name: Build and Push
+      - name: Build, tag, and push Docker image
         env:
           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+          REPOSITORY: near05-api
+          IMAGE_TAG: ${{ github.sha }}
         run: |
-          docker build -t $ECR_REGISTRY/near05-api:latest -f docker/DockerFile .
-          docker push $ECR_REGISTRY/near05-api:latest
+          docker build \
+            -t $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG \
+            -f docker/DockerFile .
 
-      - name: SSH Deploy
-        uses: appleboy/ssh-action@master
+          docker push $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG
+
+
+      - name: Deploy to EC2
+        uses: appleboy/ssh-action@v1.0.3
         with:
           host: ${{ secrets.EC2_HOST }}
           username: ec2-user
           key: ${{ secrets.EC2_SSH_KEY }}
           script: |
-            export PATH=$PATH:/usr/local/bin
-            
+            set -e
             cd ~/app
-            docker compose -f docker-compose.dev.yml pull
-            docker compose -f docker-compose.dev.yml up -d
+            
+            export IMAGE_TAG=${{ github.sha }}
+            
+            if ! docker pull $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG; then
+              echo "[Fail] Failed to pull Docker image"
+              exit 1
+            fi
+            
+            docker compose -f docker-compose.dev.yml up -d --wait
+            docker image prune -af --filter "until=72h" || true
+            
+            echo "[Success] Deployment successful"
